### ISSUE TITLE
Fixtures 20/21

### ISSUE THREAD

**Issue by ghost** [solpaul/fpl-prediction#1]
Thank you for this repository. Really nice work.
One quick question, will you also include the fixtures per player for 20/21 so we can forecast the first 10 weeks?

Thanks again!

**Comment by solpaul** [comment]
Sorry, only just saw this message (need to turn on alerts). You have all remaining fixtures for currently active players in the data/remaining_season.csv file. I update this every week. Thanks for your feedback, much appreciated.
