### ISSUE TITLE
train.csv missing

### ISSUE THREAD

**Issue by Bboofs** [solpaul/fpl-prediction#2]
From the notebook https://github.com/solpaul/fpl-prediction/blob/master/initial_fpl_data_clean.ipynb, input cell 7 is reading the file `./data/train.csv`. Could you please share how the file is generated or the structure of the file.

```
train_df = pd.read_csv(path/'train.csv', index_col=0, dtype={'season':str})
train_df = train_df[train_df['season'] != '1920']
```

**Comment by solpaul** [comment]
You can find the latest training csv file at data/train_v7.csv, and the structure of the file is explored in the 00_fpl_features.ipynb notebook. The training csv file is updated each week so you could look at the update_data_weekly.ipynb notebook to see the various functions (in helpers.py) that perform that update.
